### ISSUE TITLE
Add trigger icon ('+') not working

### ISSUE THREAD

**Issue by raumregionmensch** [raumregionmensch/rrm-plugin#24]
```
Ein Fehler trat bei der Ausführung von Python-Code auf: 

AttributeError: 'list' object has no attribute 'source_table' 
Traceback (most recent call last):
  File "C:/Users/benutzer/.qgis2/python/plugins\postgis_sampling_tool\config_dialog.py", line 199, in add_trigger
    dlg = TriggerDialog(conn, self.triggers)
  File "C:/Users/benutzer/.qgis2/python/plugins\postgis_sampling_tool\trigger_dialog.py", line 126, in __init__
    source_schema, source_table = sql_gen.source_table.split('.')
AttributeError: 'list' object has no attribute 'source_table'


Python-Version: 2.7.14 (v2.7.14:84471935ed, Sep 16 2017, 20:25:58) [MSC v.1500 64 bit (AMD64)] 
QGIS-Version: 2.18.28 Las Palmas, 6551c2a73e 

Python-Pfad:
C:/PROGRA~1/QGIS2~1.18/apps/qgis-ltr/./python/plugins\processing
C:/PROGRA~1/QGIS2~1.18/apps/qgis-ltr/./python
C:/Users/benutzer/.qgis2/python
C:/Users/benutzer/.qgis2/python/plugins
C:/PROGRA~1/QGIS2~1.18/apps/qgis-ltr/./python/plugins
C:\PROGRA~1\QGIS2~1.18\bin\python27.zip
C:\PROGRA~1\QGIS2~1.18\apps\Python27\DLLs
C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib
C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\plat-win
C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\lib-tk
C:\PROGRA~1\QGIS2~1.18\bin
C:\PROGRA~1\QGIS2~1.18\apps\Python27
C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\site-packages
C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\site-packages\jinja2-2.7.2-py2.7.egg
C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\site-packages\markupsafe-0.23-py2.7-win-amd64.egg
C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\site-packages\win32
C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\site-packages\win32\lib
C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\site-packages\Pythonwin
C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\site-packages\Shapely-1.2.18-py2.7-win-amd64.egg
C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\site-packages\wx-2.8-msw-unicode
C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\site-packages\xlrd-0.9.2-py2.7.egg
C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\site-packages\xlwt-0.7.5-py2.7.egg
C:/Users/benutzer/.qgis2//python
```
![add_trigger_issue](https://user-images.githubusercontent.com/22611509/70248080-b34f7780-177a-11ea-8a05-6712a40f8842.png)

**Comment by raumregionmensch** [comment]
The '+' icon works as expected in QGIS 3.
